from django.db.models import TextChoices


class WaterUtilityCompany(TextChoices):
    """
    Enumeration for water utility companies.
    """

    AGUAS_ANDINAS = "Aguas Andinas"
    AGUAS_ARAUCANIA = "Aguas Araucanía"
    AGUAS_CORDILLERA = "Aguas Cordillera"
    AGUAS_DE_ANTOFAGASTA = "Aguas de Antofagasta"
    AGUAS_DE_COLINA = "Aguas de Colina"
    AGUAS_DECIMA = "Aguas Décima"
    AGUAS_DEL_ALTIPLANO = "Aguas del Altiplano"
    AGUAS_DEL_VALLE = "Aguas del Valle"
    AGUAS_LA_SERENA = "Aguas La Serena"
    AGUAS_MAGALLANES = "Aguas Magallanes"
    AGUAS_MANQUEHUE = "Aguas Manquehue"
    AGUAS_PATAGONIA = "Aguas Patagonia"
    AGUAS_SAN_PEDRO_SA = "Aguas San Pedro S.A."
    AGUAS_SANTIAGO_NORTE = "Aguas Santiago Norte"
    AGUAS_SANTIAGO_PONIENTE = "Aguas Santiago Poniente"
    ALGARROBO_NORTE = "Algarrobo Norte"
    BCC_SA = "BCC S.A."
    BRISAS_DE_MIRASOL = "Brisas de Mirasol"
    COMITE_DE_AGUA_POTABLE_ALCANTARILLADO_QUEPE = (
        "Comité de Agua Potable Alcantarillado Quepe"
    )
    COOPAGUA_SANTO_DOMINGO = "Coopagua Santo Domingo"
    COOPERATIVA_MAULE = "Cooperativa Maule"
    COOPERATIVA_SAGRADA_FAMILIA = "Cooperativa Sagrada Familia"
    COOPERATIVA_SARMIENTO = "Cooperativa Sarmiento"
    COSSBO = "COSSBO"
    EMPRESA_AGUA_POTABLE_EL_COLORADO = "Empresa Agua Potable El Colorado"
    EMPRESA_SERVICIOS_SANITARIOS_DE_LA_ESTACION = (
        "Empresa Servicios Sanitarios de la Estación"
    )
    ESSBIO = "ESSBIO"
    ESVAL = "Esval"
    EXPLOTACIONES_SANITARIAS_SA = "Explotaciones Sanitarias S.A."
    HUERTOS_FAMILIARES_SA = "Huertos Familiares S.A."
    IZARRA_DE_LO_AGUIRRE = "Izarra de Lo Aguirre"
    LA_LEONERA = "La Leonera"
    LARAPINTA = "Larapinta"
    MELIPILLA_NORTE = "Melipilla Norte"
    MIRASOL_DE_ALGARROBO = "Mirasol de Algarrobo"
    NOVAGUAS_SA = "Novaguas S.A."
    NUEVA_ATACAMA = "Nueva Atacama"
    NUEVOSUR_SA = "Nuevosur S.A."
    SACYR_AGUA_CHACABUCO_SA = "Sacyr Agua Chacabuco S.A."
    SACYR_AGUA_LAMPA_SA = "Sacyr Agua Lampa S.A."
    SACYR_AGUA_SANTIAGO_SA = "Sacyr Agua Santiago S.A."
    SAN_ISIDRO = "San Isidro"
    SANITARIA_SUR = "Sanitaria Sur"
    SANTA_ROSA_DEL_PERAL = "Santa Rosa del Peral"
    SASIPA = "SASIPA"
    SMAPA = "SMAPA"
    SURALIS = "SURALIS"
    TOTORALILLO_SA = "Totoralillo S.A"
